services:
  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: elvengard_dev
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
