services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elvengard_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
