#!/bin/bash
set -e

# Is command empty, print help
[ -z "$1" ] && iex --help && exit

[[ $1 != "--app" ]] && echo "usage: ./iex [--app app_name] args" && exit
[ -z $2 ] && echo "usage: ./iex [--app app_name] args" && exit
[ ! -d "lib/$2" ] && echo "app $2 doesn't exists" && exit
[ -z $3 ] && echo "usage: ./iex [--app app_name] args" && exit

APP="$2"
shift 2

echo "===== Running '$@' into '$APP' ====="
cd "lib/$APP"
iex $@
