#!/bin/bash
set -e

# Ignored dirs
IGNORE_APPS=()

# Is command empty, print help
[ -z "$1" ] && mix help && exit

if [[ $1 =~ "--app" ]]
then
    [ -z $2 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit
    [ ! -d "lib/$2" ] && echo "app $2 doesn't exists" && exit
    [ -z $3 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit

    APP="$2"
    shift 2

    if [[ $1 =~ "--sname" ]]
    then
        [ -z $2 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit
        [ -z $3 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit

        SNAME="$2"
        shift 2

        echo "===== Running '$@' into '$APP' with sname '$SNAME' ====="
        cd "lib/$APP"
        elixir --sname $SNAME -S mix $@
    elif [[ $1 =~ "--name" ]]
    then
        [ -z $2 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit
        [ -z $3 ] && echo "usage: ./mix [--app app_name] [--(s)name name] args" && exit

        SNAME="$2"
        shift 2

        echo "===== Running '$@' into '$APP' with name '$SNAME' ====="
        cd "lib/$APP"
        elixir --name $SNAME -S mix $@
    else
        echo "===== Running '$@' into '$APP' ====="
        cd "lib/$APP"
        mix $@
    fi
else
    for APP in $(ls -d lib/*/ | sed 's,lib/,,' | sed 's/.$//')
    do
        [[ ${IGNORE_APPS[*]} =~ $APP ]] && continue;
        [ ! -f "lib/$APP/mix.exs" ] && continue;

        echo "===== Running '$@' into '$APP' ====="
        cd "lib/$APP"
        mix $@
        cd - >/dev/null
        echo
    done
fi
