#!/bin/bash
set -e

# Ignored dirs
IGNORE_APPS=(old_project,elven_database)

# Is command empty, print help
[ -z "$1" ] && mix help && exit

if [[ $1 =~ "--app" ]]
then
    [ -z $2 ] && echo "usage: ./mix [--app app_name] args" && exit
    [ ! -d $2 ] && echo "app $2 doesn't exists" && exit
    [ -z $3 ] && echo "usage: ./mix [--app app_name] args" && exit

    APP="$2"
    shift 2

    echo "===== Running '$@' into '$APP' ====="
    cd "$APP"
    mix $@
else
    for APP in $(ls -d */ | sed 's/.$//')
    do
        [[ ${IGNORE_APPS[*]} =~ $APP ]] && continue;
        [ ! -f "$APP/mix.exs" ] && continue;

        echo "===== Running '$@' into '$APP' ====="
        cd "$APP"
        mix $@
        cd - >/dev/null
        echo
    done
fi
