[package]
name = "pathfinding"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "pathfinding"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
pathfinding = "4.3.2"
