---
# tasks file for provision/roles/security

- name: install security packages
  apt:
    name: ['ufw', 'fail2ban', 'unattended-upgrades', 'logwatch']
    state: present
    update_cache: yes

## Firewall

- name: ufw | reset configuration
  ufw:
    state: reset
  tags: ufw

- name: ufw | deny all
  ufw:
    policy: deny
    state: enabled
  tags: ufw

- name: ufw | allow ssh traffic
  ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp
  tags: ufw

- name: ufw | disable ping
  replace:
    path: /etc/ufw/before.rules
    regexp: '^(-A ufw-before-input -p icmp --icmp-type [a-z-]+ -j) ACCEPT'
    replace: '\1 DROP'
    backup: yes
  tags: ufw

- name: ufw | disable ipv6 ping
  replace:
    path: /etc/ufw/before6.rules
    regexp: '^(-A ufw6-before-input -p icmpv6 --icmpv6-type [a-z-]+ -j) ACCEPT'
    replace: '\1 DROP'
    backup: yes
  tags: ufw

- name: ufw | reload and enable
  ufw:
    state: "{{ item }}"
  loop:
    - reloaded
    - enabled
  tags: ufw

## Configure automatic updates

- name: apt | adjust update intervals
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
  tags: apt_periodic

## Configure Logwatch

- name: logwatch | set up Postfix to relay mail
  debconf:
    name: postfix
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }
  tags: logwatch

- name: logwatch | email log summary daily
  lineinfile:
    dest: /etc/cron.daily/00logwatch
    regexp: "^/usr/sbin/logwatch"
    line: "/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
    state: present
    create: yes
  tags: logwatch

## Lockdown ssh access

- name: ssh | change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Port\s'
    line: "Port {{ ssh_port }}"
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  tags: ssh

  ## TODO: Fail2ban rules
