---
# tasks file for provision/roles/security

- name: install security packages
  apt:
    name:
      - ufw
      - fail2ban
      - unattended-upgrades
      - logwatch
      - sendmail
      - net-tools
    state: present
    update_cache: yes

## Create sudo user

- name: sudo_user | create the sudo user
  user:
    name: "{{ sudo_user }}"
    password: '{{ sudo_password | password_hash("sha512") }}'
    shell: "{{ sudo_shell }}"
    groups: sudo
    createhome: yes

- name: sudo_user | add the host ssh key to authorized_key
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ lookup('file', item) }}"
    state: present
  loop: "{{ public_keys }}"

## Firewall

- name: ufw | reset configuration
  ufw:
    state: reset
  tags: ufw

- name: ufw | deny all
  ufw:
    policy: deny
    state: enabled
  tags: ufw

- name: ufw | allow ssh traffic
  ufw:
    rule: limit
    port: "{{ ssh_port | string }}"
    proto: tcp
  tags: ufw

- name: ufw | disable ping
  replace:
    path: /etc/ufw/before.rules
    regexp: '^(-A ufw-before-input -p icmp --icmp-type [a-z-]+ -j) ACCEPT'
    replace: '\1 DROP'
    backup: yes
  tags: ufw

- name: ufw | disable ipv6 ping
  replace:
    path: /etc/ufw/before6.rules
    regexp: '^(-A ufw6-before-input -p icmpv6 --icmpv6-type [a-z-]+ -j) ACCEPT'
    replace: '\1 DROP'
    backup: yes
  tags: ufw

- name: ufw | reload and enable
  ufw:
    state: "{{ item }}"
  loop:
    - reloaded
    - enabled
  tags: ufw

## Configure automatic updates

- name: apt | adjust update intervals
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
  tags: apt_periodic

## Configure Postfix for Gmail

- include: postfix_gmail.yml
  when: postfix_gmail.enable

## Configure Logwatch

- name: logwatch | modify host file for postmail
  lineinfile:
    dest: /etc/hosts
    insertafter: '^127.0.0.1 '
    line: 127.0.0.1 localhost.localdomain
    firstmatch: no
    create: yes

- name: logwatch | email log summary daily
  lineinfile:
    dest: /etc/cron.daily/00logwatch
    regexp: "^/usr/sbin/logwatch"
    line: "/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high --service all --range today"
    state: present
    create: yes
  tags: logwatch

## Lockdown ssh access

- name: ssh | change ssh port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Port\s'
    line: "Port {{ ssh_port }}"
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | remove banner
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#Banner '
    line: 'Banner none'
    state: present
  notify: restart ssh
  tags: ssh

- name: ssh | remove banner (Debian)
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'DebianBanner no'
    state: present
  notify: restart ssh
  tags: ssh

  ## TODO: Fail2ban rules
