IMAGE_NAME = "debian/buster64"

Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.ssh.insert_key = true

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
  end

  config.vm.define "build" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "192.168.50.10"
    node.vm.hostname = "build"
    # node.vm.provision "ansible" do |ansible|
    #     # ansible.verbose = "v"
    #     ansible.playbook = "provision/playbook1.yml"
    # end
  end
end
