IMAGE_NAME = "debian/buster64"

Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.ssh.insert_key = true
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
  end

  config.vm.define "builder" do |node|
    node.vm.box = IMAGE_NAME
    node.vm.network "private_network", ip: "192.168.50.10"
    node.vm.hostname = "builder"
    node.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/builder.yml"
        ansible.groups = { "builders" => ["builder"] }
    end
  end
end
