---
# tasks file for ./provision/roles/create_user

- name: create the elixir user
  user:
    name: "{{ elixir_user }}"
    shell: "{{ elixir_shell }}"
    createhome: yes

- name: add the host ssh key to authorized_key
  authorized_key:
    user: "{{ elixir_user }}"
    key: "{{ lookup('file', item) }}"
    state: present
  loop: "{{ public_keys }}"

# - name: Add deploy user to sudoers
#   lineinfile:
#     dest: /etc/sudoers
#     regexp: "{{ elixir_user }} ALL"
#     line: "{{ elixir_user }} ALL=(ALL) ALL"
#     state: present

- name: disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify: restart ssh
